// Authentication
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED_SUCCESS = "USER_LOADED_SUCCESS";
export const USER_LOADED_FAIL = "USER_LOADED_FAIL";
export const LOGOUT = "LOGOUT";
export const AUTHENTICATED_SUCCESS = "AUTHENTICATED_SUCCESS";
export const AUTHENTICATED_FAIL = "AUTHENTICATED_FAIL";

// Alerts
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Channels
export const GET_CHANNELS_SUCCESS = "GET_CHANNELS_SUCCESS";
export const GET_CHANNELS_FAIL = "GET_CHANNELS_FAIL";
export const GET_CHANNEL_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_CHANNEL_FAIL = "GET_REVIEW_FAIL";
export const CREATE_CHANNEL_SUCCESS = "CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_FAIL = "CREATE_CHANNEL_FAIL";
export const DELETE_CHANNEL_SUCCESS = "DELETE_CHANNEL_SUCCESS";
export const DELETE_CHANNEL_FAIL = "DELETE_CHANNEL_FAIL";
export const GET_REVIEW_CHANNEL_SUCCESS = "GET_REVIEW_CHANNEL_SUCCESS";
export const GET_REVIEW_CHANNEL_FAIL = "GET_REVIEW_CHANNEL_FAIL";
export const UPDATE_REVIEW_CHANNEL_SUCCESS = "UPDATE_REVIEW_CHANNEL_SUCCESS";
export const UPDATE_REVIEW_CHANNEL_FAIL = "UPDATE_REVIEW_CHANNEL_FAIL";

// Messagers
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
export const CREATE_MESSAGE_SUCCESS = "CREATE_MESSAGE_SUCCESS";
export const CREATE_MESSAGE_FAIL = "CREATE_MESSAGE_FAIL";
export const DELETE_MESSAGE_SUCCESS = "DELETE_MESSAGE_SUCCESS";
export const DELETE_MESSAGE_FAIL = "DELETE_MESSAGE_FAIL";

// Direct Messages
export const GET_DIRECT_MESSAGES_SUCCESS = "GET_DIRECT_MESSAGES_SUCCESS";
export const GET_DIRECT_MESSAGES_FAIL = "GET_DIRECT_MESSAGES_FAIL";
